version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18  # Specify Node.js version
    commands:
      - echo "Installing Maven 3.8.8 manually..."
      - wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip
      - unzip apache-maven-3.8.8-bin.zip -d /opt
      - ln -s /opt/apache-maven-3.8.8 /opt/maven
      - export M2_HOME=/opt/maven
      - export PATH=$M2_HOME/bin:$PATH
      - echo "Maven version:"
      - mvn -v
  build:
    commands:
      - echo Building project with skipped tests...
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
