version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
      nodejs: 18  # Specify Node.js version
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - mvn -v
      - node -v
      - npm -v
      - echo Installing Node.js dependencies...
      - npm install
  build:
    commands:
      - echo Building project with skipped tests...
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
