version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven..."
      - apt update && apt install -y maven
      - mvn -v
  build:
    commands:
      - echo "Building Spring Boot project..."
      - mvn package -DskipTests
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
