version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  pre_build:
    commands:
      - echo Cleaning previous builds...
      - mvn clean
  build:
    commands:
      - echo Building the project...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build complete
      - echo Preparing artifacts for deployment...

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
