version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - echo Building the project...
      - mvn clean package -DskipTests
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
