version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - mvn -v
      - ls -al
  build:
    commands:
      - echo Building project with skipped tests...
      - mvn package -DskipTests
artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
