version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Installing Maven manually..."
      - apt update
      - apt install -y wget unzip
      - wget https://downloads.apache.org/maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip
      - unzip apache-maven-3.8.8-bin.zip -d /opt
      - ln -s /opt/apache-maven-3.8.8 /opt/maven
      - export M2_HOME=/opt/maven
      - export PATH=${M2_HOME}/bin:${PATH}
      - mvn -v
  pre_build:
    commands:
      - echo "Cleaning project..."
      - mvn clean
  build:
    commands:
      - echo "Packaging Spring Boot app..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Build successful."

artifacts:
  files:
    - target/*.jar
    - appspec.yml
    - scripts/**/*
